[pytest]
DJANGO_SETTINGS_MODULE = config.settings
# Add the apps directory to the python path so pytest can find the modules
pythonpath = . apps
python_files = tests.py test_*.py *_tests.py
# This prevents pytest from skipping tests that require a database
django_find_project = true